services:
  mysql-app-db:
    image: juanmananesprieto/mi_mysql_app:latest
    container_name: mysql_app_db_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'tu_password_root_muy_seguro' # ¡CAMBIA ESTO!
      MYSQL_DATABASE: 'mi_app_db'
      MYSQL_USER: 'user_app'
      MYSQL_PASSWORD: 'password_app_muy_seguro' # ¡CAMBIA ESTO!
    ports:
      - "3306:3306"
    volumes:
      - mysql_app_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  apps-tomcat: # Servicio Tomcat unificado
    build:
      context: . # El contexto es la raíz del proyecto, donde se encuentra Dockerfile.tomcat-combined
      dockerfile: Dockerfile.tomcat-combined # Especifica el nuevo Dockerfile
      args:
        # Rutas a los archivos WAR relativas al contexto de construcción (.)
        EMPLEADOS_WAR_PATH: ./empleados/build/libs/empleados.war
        ADMINISTRACION_WAR_PATH: ./administracion/build/libs/administracion.war
    container_name: apps_tomcat_container
    restart: unless-stopped
    ports:
      # Mapea un solo puerto del host (ej. 8080) al puerto 8080 de Tomcat
      # Tus aplicaciones estarán disponibles en http://localhost:8080/empleados y http://localhost:8080/administracion
      - "8080:8080"
    environment:
      # Variables de entorno comunes para ambas aplicaciones Spring Boot
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/mi_app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 'user_app'
      SPRING_DATASOURCE_PASSWORD: 'password_app_muy_seguro' # ¡CAMBIA ESTO!
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'validate'
      # CATALINA_OPTS: "-Xms512m -Xmx1024m" # Considera aumentar la memoria para dos aplicaciones
    depends_on:
      mysql-app-db:
        condition: service_healthy # Espera a que mysql-app-db esté saludable
    networks:
      - app-network

volumes:
  mysql_app_data:

networks:
  app-network:
    driver: bridge
